name: Crystal Palace
favicon: null
layout_spectrum: 0.82609
typography_spectrum: 0.63719
title: 'Crystal Palace, London'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-225961-39
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22252a'
    - '#e15653'
    - '#947256'
    - '#c5a66f'
    - '#f6d7a9'
  brandStrength: 0.25
  lightness: 0.21571784582920372
  saturation: 0.8448816314339638
  rhythmicContrast: 0.4383411316666752
purpose: []
