name: Crystal Palace
favicon: null
layout_spectrum: 0.8394360214006156
typography_spectrum: 0.13349752011708915
title: 'Crystal Palace, London'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-225961-39
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3154495421331376
  lightness: 0.21571784582920372
  saturation: 0.8448816314339638
  rhythmicContrast: 0.4383411316666752
purpose: []
