name: Crystal Palace
favicon: null
layout_spectrum: 0.57408
typography_spectrum: 0.13349752011708915
title: 'Crystal Palace, London'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-225961-39
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9b8868'
    - '#bfad97'
    - '#453621'
    - '#7d6034'
    - '#070508'
  brandStrength: 0.25
  lightness: 0.21571784582920372
  saturation: 0.8448816314339638
  rhythmicContrast: 0.4383411316666752
purpose: []
